#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
setxkbmap -option caps:super &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4 #2
bspc config window_gap          0 #12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#program rules
bspc rule -a nitrogen state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on


#mouse control
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
